### ISSUE TITLE
curl: (22) The requested URL returned error: 401 

### ISSUE THREAD

**Issue by HydrolienF** [Popsiclestick/gist-sync-action#3]
I've got this error when using your tools with:
```
    - name: Generate version Badge
      uses: popsiclestick/gist-sync-action@v1.2.0
      id: sync
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gist_url: https://gist.githubusercontent.com/HydrolienF/c7dbc5d2d61b749ff6878e93afdaf53e/raw/version.json
        gist_title: version.json
        gist_description: ""
        github_file: "temp"
```
I have create a authentification key for gist only, but authetification fail.
Is there something wrong in my code ?
